pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID=credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY=credentials('AWS_SECRET_ACCESS_KEY')
        def JFROG_KEY=credentials('jfrog')
    }
    stages {
        stage('git checkout') {
            steps {
                git branch: 'main', credentialsId: 'git-rnaik', url: 'https://github.com/rknaik76/demojenkins.git'
            }
        }
        stage('IMAGE BUILD') {
            steps {
                sh '''
                docker login --username rknaik76@gmail.com --password $JFROG_KEY rknaik76.jfrog.io
                docker build -t rknaik76.jfrog.io/drinks-docker/hellonode:${BUILD_NUMBER} .
                docker push rknaik76.jfrog.io/drinks-docker/hellonode:${BUILD_NUMBER}
                '''
            }
        }
        stage('EKS DEPLPY') {
            input {
                message "Please Approve for Deployment"
            }
            steps {
                sh '''
                chmod -R 755 ./jenkins/scripts
                ./jenkins/scripts/prepare_deployment.bash ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} terraformEKScluster ${BUILD_NUMBER}
                ./jenkins/scripts/update_deployment.bash drinks ./kubernetes/pod.yaml drinks rknaik76.jfrog.io/drinks-docker/hellonode ${BUILD_NUMBER}
                '''
            }
        }
        // stage('EKS SVC CREATE') {
        //     steps {
        //         sh label: 'EKS SVC CREATE', script: "kubectl create -f ./kubernetes/service.yaml"
        //     }
        // }
    }
}