pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID=credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY=credentials('AWS_SECRET_ACCESS_KEY')
        JFROG_PAAS=credentials('jfrog')
        EKS_CLUSTER_NAME="terraformEKScluster"
        JFROG_REPO_URL="rknaik76.jfrog.io/drinks-docker/hellonode"
        CONTAINER_NAME="drinks"
        KUBE_DEPLOYMENT_YAML="./kubernetes/pod.yaml"
    }
    stages {
        stage('git checkout') {
            steps {
                git branch: 'main', credentialsId: 'git-rnaik', url: 'https://github.com/rknaik76/demojenkins.git'
            }
        }
        stage('IMAGE BUILD') {
            steps {
                sh """
                docker login --username rknaik76@gmail.com --password $JFROG_PAAS_PSW rknaik76.jfrog.io
                docker build -t rknaik76.jfrog.io/drinks-docker/hellonode:${BUILD_NUMBER} .
                docker push rknaik76.jfrog.io/drinks-docker/hellonode:${BUILD_NUMBER}
                """
            }
        }
        stage('EKS DEPLPY') {
            input {
                message "Please Approve for Deployment"
            }
            steps {
                sh '''
                chmod -R 755 ./jenkins/scripts
                ./jenkins/scripts/prepare_deployment.bash ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} ${EKS_CLUSTER_NAME} ${BUILD_NUMBER}
                ./jenkins/scripts/update_deployment.bash drinks ${KUBE_DEPLOYMENT_YAML} ${CONTAINER_NAME} ${JFROG_REPO_URL} ${BUILD_NUMBER}
                '''
            }
        }
        // stage('EKS SVC CREATE') {
        //     steps {
        //         sh label: 'EKS SVC CREATE', script: "kubectl create -f ./kubernetes/service.yaml"
        //     }
        // }
    }
}